config/routes.rb
Rails.application.routes.draw do

  resources :projects

  resources :applications
  resources :impacted_applications
  resources :business_areas
  resources :initiatives
  
  
  
  root 'projects#index'

end

app/models/initiative.rb
class Initiative < ActiveRecord::Base
  belongs_to :business_area
  has_many :projects
end

app/controllers/initiatives_controller.rb
class InitiativesController < ApplicationController

  def index
    @initiatives = Initiative.all
  end
  
  def show
    @initiative = Initiative.find(params[:id]) 
  end
  
  def new
    @initiative = Initiative.new
  end

 def edit
    set_initiative
 end
  
 	def update
    set_initiative

		if @initiative.update(params[:initiative].permit(:name, :priority, :business_area_id))
      flash[:notice] = 'Initiative Updated'
			redirect_to @initiative
		else
			render 'edit'
		end
	end

  def destroy
    set_initiative
    @initiative.destroy
    respond_to do |format|
      format.html { redirect_to initiatives_url, notice: 'Initiative was successfully destroyed.' }
      format.json { head :no_content }
    end
  end
  
  def create
    @initiative = Initiative.new(params[:initiative].permit(:name, :priority, :business_area_id))

    respond_to do |format|
      if @initiative.save
        format.html { redirect_to @initiative, notice: 'Initiative was successfully created.' }
        format.json { render :show, status: :created, location: @initiative }
      else
        format.html { render :new }
        format.json { render json: @initiative.errors, status: :unprocessable_entity }
      end
    end
  end

private
  def set_initiative
      @initiative = Initiative.find(params[:id]) 
  end
end

app/helpers/initiative_helper.rb
module InitiativeHelper
end

app/views/initiatives/_form.html.erb
<%= form_for @initiative, :html => { :class => "form-horizontal initiative" } do |f| %>

    <% if @initiative.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@initiative.errors.count, "error") %> prohibited this initiative from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @initiative.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="control-group">
    <%= f.label :name, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :name, :class => 'form-control' %>
    </div>
    <%= error_span(@initiative[:name]) %>
  </div>
  <div class="control-group">
    <%= f.label :priority, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :priority, :class => 'form-control' %>
    </div>
    <%= error_span(@initiative[:priority]) %>
  </div>
  <div class="control-group">
    <%= f.label :business_area_id, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :business_area_id, :class => 'form-control' %>
    </div>
    <%= error_span(@initiative[:business_area_id]) %>
  </div>


  <%= f.submit nil, :class => 'btn btn-primary' %>
  <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
            initiatives_path, :class => 'btn btn-default' %>

<% end %>

app/views/initiatives/_initiative.html.erb
<tr>
  <td><%= link_to 'View', initiative %></td>
  <td><%= initiative.priority %></td>
  <td><%= initiative.name %></td>
  <td><%= initiative.projects.size %></td>
</tr>

app/views/initiatives/edit.html.erb
<%- model_class = Initiative -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/initiatives/index.html.erb
<%- model_class = Initiative -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:name) %></th>
      <th><%= model_class.human_attribute_name(:priority) %></th>
      <th><%= model_class.human_attribute_name(:business_area_id) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @initiatives.each do |initiative| %>
      <tr>
        <td><%= link_to initiative.id, initiative_path(initiative) %></td>
        <td><%= initiative.name %></td>
        <td><%= initiative.priority %></td>
        <td><%= initiative.business_area.name %></td>
        <td><%=l initiative.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_initiative_path(initiative), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      initiative_path(initiative),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_initiative_path,
            :class => 'btn btn-primary' %>

app/views/initiatives/new.html.erb
<%- model_class = Initiative -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/initiatives/show.html.erb
<%- model_class = Initiative -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:name) %>:</strong></dt>
  <dd><%= @initiative.name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:priority) %>:</strong></dt>
  <dd><%= @initiative.priority %></dd>
  <dt><strong><%= model_class.human_attribute_name(:business_area_id) %>:</strong></dt>
  <dd><%= @initiative.business_area.name %></dd>
</dl>

<% if @initiative.projects.size > 0 %>
<table class="table table-striped">
  <thead>
    <tr>
				<th> </th>
				<th>Ref Number</th>
				<th>Project</th>
        <th># of Impacted Applications
		</tr>
  <thead>
		<tbody>
      <%= render partial: "projects/project", collection: @initiative.projects %>
		</tbody>
	</table>
<% else %>
	<p>No applications identified</p>
<% end %>

<%= link_to t('.back', :default => t("helpers.links.back")),
              initiatives_path, :class => 'btn btn-default'  %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_initiative_path(@initiative), :class => 'btn btn-default' %>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              initiative_path(@initiative),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>