config/routes.rb
Rails.application.routes.draw do

  resources :projects

  resources :applications
  resources :impacted_applications
  resources :business_areas
  resources :initiatives
  
  
  
  root 'projects#index'

end

app/models/impacted_application.rb
class ImpactedApplication < ActiveRecord::Base
  belongs_to :project
  belongs_to :application
  has_one  :business_area, :through => :application
end

app/controllers/impacted_applications_controller.rb
class ImpactedApplicationsController < ApplicationController

  def index
    @impacted_applications = ImpactedApplication.all
  end
  
  def show
    @impacted_application = ImpactedApplication.find(params[:id]) 
  end
  
  def new
    @impacted_application = ImpactedApplication.new
  end

 def edit
    set_impacted_application
 end
  
 	def update
    set_impacted_application

		if @impacted_application.update(params[:impacted_application].permit(:name, :priority, :business_area_id))
      flash[:notice] = 'Impacted Application Updated'
			redirect_to @impacted_application
		else
			render 'edit'
		end
	end

  def destroy
    set_impacted_application
    @impacted_application.destroy
    respond_to do |format|
      format.html { redirect_to impacted_applications_url, notice: 'Impacted Application was successfully destroyed.' }
      format.json { head :no_content }
    end
  end
  
  def create
    @impacted_application = ImpactedApplication.new(params[:impacted_application].permit(:project_id, :application_id))

    respond_to do |format|
      if @impacted_application.save
        format.html { redirect_to @impacted_application, notice: 'Impacted Application was successfully created.' }
        format.json { render :show, status: :created, location: @impacted_application }
      else
        format.html { render :new }
        format.json { render json: @impacted_application.errors, status: :unprocessable_entity }
      end
    end
  end

  
private
  def set_impacted_application
      @impacted_application = ImpactedApplication.find(params[:id]) 
  end
end

app/helpers/impacted_application_helper.rb
module ImpactedApplicationHelper
end

app/views/impacted_applications/_form.html.erb
<%= form_for @impacted_application, :html => { :class => "form-horizontal impacted_application" } do |f| %>

    <% if @impacted_application.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@impacted_application.errors.count, "error") %> prohibited this impacted_application from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @impacted_application.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="control-group">
    <%= f.label :project_id, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :project_id, :class => 'form-control' %>
    </div>
    <%= error_span(@impacted_application[:project_id]) %>
  </div>
  <div class="control-group">
    <%= f.label :application_id, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :application_id, :class => 'form-control' %>
    </div>
    <%= error_span(@impacted_application[:application_id]) %>
  </div>


  <%= f.submit nil, :class => 'btn btn-primary' %>
  <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
            impacted_applications_path, :class => 'btn btn-default' %>

<% end %>

app/views/impacted_applications/_impacted_application.html.erb
<tr>
  <td><%= link_to impacted_application.application.name + " (" + impacted_application.application.ams_id.to_s + ")", impacted_application.application %></td>
  <td><%= impacted_application.business_area.name%></td>

</tr>

app/views/impacted_applications/edit.html.erb
<%- model_class = ImpactedApplication -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/impacted_applications/index.html.erb
<%- model_class = ImpactedApplication -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:project_id) %></th>
      <th><%= model_class.human_attribute_name(:application_id) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @impacted_applications.each do |impacted_application| %>
      <tr>
        <td><%= link_to impacted_application.id, impacted_application_path(impacted_application) %></td>
        <td><%= impacted_application.project.ref_num %></td>
        <td><%= impacted_application.application.name %></td>
        <td><%=l impacted_application.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_impacted_application_path(impacted_application), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      impacted_application_path(impacted_application),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_impacted_application_path,
            :class => 'btn btn-primary' %>

app/views/impacted_applications/new.html.erb
<%- model_class = ImpactedApplication -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/impacted_applications/show.html.erb
<%- model_class = ImpactedApplication -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:project_id) %>:</strong></dt>
  <dd><%= @impacted_application.project.project_name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:application_id) %>:</strong></dt>
  <dd><%= @impacted_application.application.short_name %></dd>
</dl>

<%= link_to t('.back', :default => t("helpers.links.back")),
              impacted_applications_path, :class => 'btn btn-default'  %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_impacted_application_path(@impacted_application), :class => 'btn btn-default' %>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              impacted_application_path(@impacted_application),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>